version: '3' # Version of Docker Compose
services:
  app:
    image: ghcr.io/somnath-more/nodejs-portfolio:latest
    container_name: node-app
    ports:
      - '5555:5555' # Expose your app on port 5555
    environment:
      - PORT=5555
      - DB_CONNECTION_URL=mongodb://mongo:27017/website_tut # MongoDB connection
    depends_on:
      - mongo # Ensure MongoDB container starts first
    command: npm start # Start the Node.js app
    networks:
      - node-network

  mongo:
    image: mongo:latest # Use latest MongoDB image
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=website_tut # Initialize the database
    volumes:
      - mongodb_data:/data/db # Persist MongoDB data
    ports:
      - '27017:27017' # Expose MongoDB port
    networks:
      - node-network

# Persist data across container restarts
volumes:
  mongodb_data:
    driver: local

# Network definition
networks:
  node-network:
    driver: bridge
