version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '5555:5555'
    environment:
      - PORT=5555
      - DB_CONNECTION_URL=mongodb://mongo:27017/website_tut
    depends_on:
      - mongo
    command: npm start
    networks:
      - node-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: website_tut
    volumes:
      - mongodb_data:/data/db # Mount a volume to persist MongoDB data
    ports:
      - '27017:27017'
    networks:
      - node-network

volumes:
  mongodb_data:
    driver: local # This is the Docker volume where MongoDB data will be stored
