name: FullStack Frontend React
on:
   push:
    branches:
      - main
      - deployment
    paths:
      - 'Full-Stack/frontend/**'
      - '.github/workflows/fullstack-frontend*'
   pull_request:
    types: [opened, reopened,synchronize]
permissions:
    id-token: write
    contents: read
jobs:
  fullstack-frontend:
     runs-on: ubuntu-latest
     timeout-minutes: 10
     defaults:
      run:
        working-directory: Full-Stack/frontend/

     steps:
     - name: Checkout the code repo
       uses: actions/checkout@v2

     - name: Install dependencies
       run: npm install 

     - name: Build the app
       run: npm  run build

     - name: Login to GHCR Registry
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.PAT_TOKEN }}
     - name: Build and push
       uses: docker/build-push-action@v6
       with:
          push: true
          context: Full-Stack/frontend/
          tags: |
            ghcr.io/somnath-more/fullstack-frontend-todo:latest
            ghcr.io/somnath-more/fullstack-frontend-todo:${{ github.sha}}

    #  - name: Set up AWS CLI
    #    uses: aws-actions/configure-aws-credentials@v1
    #    with:
    #           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #           aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
    #           aws-region: us-east-2 
  
     - name: Deploy on EC2
       env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
       run: |
           echo "$EC2_KEY" > key.pem
           chmod 400 key.pem
           ssh -o StrictHostKeyChecking=no -i key.pem $EC2_HOST@$EC2_USER << EOF
           docker login ghcr.io -u ${{ github.actor }} -p $PAT_TOKEN
           docker pull ghcr.io/somnath-more/fullstack-frontend-todo:${{ github.sha }}
           docker stop fullstack-frontend-todo || true
           docker rm fullstack-frontend-todo || true
           docker run -itd -p 9090:80 --name=fullstack-frontend-todo ghcr.io/somnath-more/fullstack-frontend-todo:${{ github.sha }}
           echo "Deployed on EC2 successfully!"
           EOF